<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'install_source' => 'Docker',
	'db_host' => 'database',
	'db_name' => 'mautic',
	'db_user' => 'root',
	'db_password' => 'password',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.23',
	'mailer_from_name' => 'Motaword',
	'mailer_from_email' => 'it@motaword.com',
	'mailer_transport' => 'mautic.transport.amazon',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => 'AKIAIIZI7AJFOT2DATMQ',
	'mailer_password' => 'zfATgvUZ3gqvfqy88E9ZXk5HpxtzUkao5C7DlIUF',
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '72d50fb4c3402a2ebcbabf9fe2f5cc86776d49001cb1b4aeb17814096a5b7161',
	'site_url' => 'http://localhost:8085',
);
